packages:
  - packages/*
  - widgets/*
  - modules/*

catalog:
  '@eslint/js': ^9.32.0
  '@prettier/plugin-xml': ^3.4.2
  eslint: ^9.32.0
  prettier: ^3.6.2

enableGlobalVirtualStore: false

publicHoistPattern:
  - '*prettier*'
